version: 1.0.{build}
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- cmd: >-
    dotnet test test\TrackTv.DataRetrieval.Tests

    dotnet test test\TrackTv.Models.Tests
    
    dotnet test test\TrackTv.Services.Tests