version: 1.0.{build}
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- cmd: >-
    dotnet test test\TrackTv.DataRetrieval.Tests\TrackTv.DataRetrieval.Tests.csproj

    dotnet test test\TrackTv.Models.Tests\TrackTv.Models.Tests.csproj
    
    dotnet test test\TrackTv.Services.Tests\TrackTv.Services.Tests.csproj