version: '3.6'

networks:
  br0:

volumes:
  backend-src:
    driver_opts:
      type: none
      device: ${backend_src}
      o: bind
  frontend-src:
    driver_opts:
      type: none
      device: ${frontend_src}
      o: bind
  db-data:

services:
  db:
    image: postgres
    restart: unless-stopped
    networks:
      br0:
        aliases:
          - db
    ports:
      - "4201:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${db_username}
      - POSTGRES_PASSWORD=${db_password}
  backend:
    image: microsoft/dotnet:2.1-sdk-alpine3.7
    restart: unless-stopped
    volumes:
      - backend-src:/app
    networks:
      br0:
        aliases:
          - backend
    working_dir: /app/TrackTv.WebServices
    entrypoint: "dotnet watch run"
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - frontend-src:/app
    networks:
      - br0    
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "4200:80"  