export const globalActions = {
  GLOBAL_ERROR: 'GLOBAL/GLOBAL_ERROR',

  LOGIN_USER: 'GLOBAL/LOGIN_USER',
  LOGOUT_USER: 'GLOBAL/LOGOUT_USER',

  START_TRANSITION: 'GLOBAL/START_TRANSITION',
  END_TRANSITION: 'GLOBAL/END_TRANSITION',
};
